### ISSUE TITLE
sample.py

### ISSUE THREAD

**Issue by zkhshub** [yeardreamA0306/monty_hall#2]
# 설명

sample.py를 생성합니다.

## To-do
- [ ] sample.py 생성
- [ ] sample.py 내용 작성
- [ ] 사용자가 선택하여 pop하도록 함수화

**Comment by jun-suk** [comment]
화이팅
