### ISSUE TITLE
result(user_choice):

### ISSUE THREAD

**Issue by goldcece** [yeardreamA0306/monty_hall#6]
# 설명

monty_hall 사용자의 선택을 받아서 선택 유지(stay) 또는 선택 바꿈(switch)의 결과를 반환해주는 result 함수를 정의하여 기능을 추가한다.

## To-do
- [ ] 코드 이해
- [ ] 함수 정의와 변수 선언(global)
- [ ] 코드 실행 확인
- [ ] git push and pull request
